on:
  push:
    branches:
      - docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
